version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/.npm
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test

workflows:
  orb-free-workflow:
    jobs:
      - test
