version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Run lint
      - run:
          command: yarn prettier
          name: Run prettier
      #- run:
      #    command: yarn test
      #    name: Run tests

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
